from datetime import datetime, timezone
from fastapi import APIRouter, Request
from fastapi.responses import PlainTextResponse

from ..config import (
    DEFAULT_API_KEY,
    INSTALL_GIT_AI_VERSION,
    INSTALL_GITHUB_BASE,
    INSTALL_GITHUB_BASE_FALLBACK,
    INSTALL_TEAM_NAME,
    INSTALL_HOOK_REPAIR_INTERVAL_MIN,
    INSTALL_REPO,
)

router = APIRouter(tags=["install"])

BUILD_TS = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")


def _intro(kind: str) -> str:
    return (
        f"# Generated by Git-AI Collector ({kind}) · "
        f"version={INSTALL_GIT_AI_VERSION} · built={BUILD_TS}"
    )


# ─────────────────────────────────────────────────────────
# Embedded helper scripts (served via /scripts/* endpoints)
# ─────────────────────────────────────────────────────────

CC_SWITCH_PATCH_PY = r'''#!/usr/bin/env python3
"""cc-switch compatibility: inject git-ai hooks into every provider config
so that hooks survive API endpoint switching.

Backups the cc-switch.db before mutating (kept for 7 days)."""
import sqlite3, json, os, platform, re, shutil, time, glob

def git_ai_path():
    if platform.system() == "Windows":
        return os.path.join(os.path.expanduser("~"), ".git-ai", "bin", "git-ai.exe")
    return os.path.join(os.path.expanduser("~"), ".git-ai", "bin", "git-ai")

def to_hook_path(p):
    """Convert Windows path to git-bash style for Claude Code hooks."""
    p = p[4:] if p.startswith("\\\\?\\") else p
    if len(p) >= 2 and p[1] == ":":
        return "/" + p[0].lower() + p[2:].replace("\\", "/")
    return p

def is_git_ai_claude_hook(hook):
    if not isinstance(hook, dict):
        return False
    cmd = hook.get("command", "")
    return isinstance(cmd, str) and "checkpoint claude" in cmd

def patch_claude_config(cfg, claude_cmd):
    if not isinstance(cfg, dict):
        return cfg, False
    hooks = cfg.get("hooks")
    hooks = hooks if isinstance(hooks, dict) else {}
    changed = hooks is not cfg.get("hooks")

    for evt in ("PreToolUse", "PostToolUse"):
        blocks = hooks.get(evt)
        blocks = blocks if isinstance(blocks, list) else []
        cleaned_blocks = []
        catch_all = None

        for block in blocks:
            if not isinstance(block, dict):
                changed = True
                continue
            new_block = dict(block)
            is_catch_all = new_block.get("matcher") in ("*", None)
            old_hooks = new_block.get("hooks")
            old_hooks = old_hooks if isinstance(old_hooks, list) else []
            new_hooks = [
                h for h in old_hooks
                if not is_git_ai_claude_hook(h)
                or (is_catch_all and isinstance(h, dict) and h.get("command") == claude_cmd)
            ]
            if len(new_hooks) != len(old_hooks):
                changed = True
            new_block["hooks"] = new_hooks
            if is_catch_all and catch_all is None:
                catch_all = new_block
            if new_hooks or len(old_hooks) == 0:
                cleaned_blocks.append(new_block)

        if catch_all is None:
            catch_all = {"matcher": "*", "hooks": []}
            cleaned_blocks.append(catch_all)
            changed = True

        if not any(
            isinstance(h, dict) and h.get("command") == claude_cmd
            for h in catch_all.get("hooks", [])
        ):
            catch_all.setdefault("hooks", []).append({"type": "command", "command": claude_cmd})
            changed = True

        if hooks.get(evt) != cleaned_blocks:
            hooks[evt] = cleaned_blocks
            changed = True

    if cfg.get("hooks") != hooks:
        cfg["hooks"] = hooks
        changed = True
    return cfg, changed

def patch_codex_toml(toml_s):
    if not isinstance(toml_s, str):
        return toml_s, False

    lines = toml_s.splitlines()
    has_trailing_newline = toml_s.endswith("\n")
    features_start = None
    next_table = len(lines)

    for i, line in enumerate(lines):
        if re.match(r"^\s*\[features\]\s*(?:#.*)?$", line):
            features_start = i
            continue
        if features_start is not None and i > features_start and re.match(r"^\s*\[", line):
            next_table = i
            break

    if features_start is None:
        suffix = "\n" if toml_s and not has_trailing_newline else ""
        return toml_s.rstrip() + suffix + "\n[features]\ncodex_hooks = true\n", True

    for i in range(features_start + 1, next_table):
        if re.match(r"^\s*codex_hooks\s*=", lines[i]):
            if re.match(r"^\s*codex_hooks\s*=\s*true\s*(?:#.*)?$", lines[i]):
                return toml_s, False
            lines[i] = "codex_hooks = true"
            out = "\n".join(lines)
            if has_trailing_newline:
                out += "\n"
            return out, True

    lines.insert(features_start + 1, "codex_hooks = true")
    out = "\n".join(lines)
    if has_trailing_newline:
        out += "\n"
    return out, True

def backup_db(db):
    """Create a timestamped copy; prune backups older than 7 days."""
    ts = time.strftime("%Y%m%d-%H%M%S")
    dst = db + ".bak." + ts
    try:
        shutil.copy2(db, dst)
    except Exception:
        return None
    cutoff = time.time() - 7 * 86400
    for old in glob.glob(db + ".bak.*"):
        try:
            if os.path.getmtime(old) < cutoff:
                os.remove(old)
        except Exception:
            pass
    return dst

def main():
    db = os.path.join(os.path.expanduser("~"), ".cc-switch", "cc-switch.db")
    if not os.path.isfile(db):
        return
    bp = git_ai_path()
    if not os.path.isfile(bp):
        return
    hp = to_hook_path(bp)
    claude_cmd = hp + " checkpoint claude --hook-input stdin"

    backup_db(db)
    conn = sqlite3.connect(db)
    cur = conn.cursor()
    n = 0

    try:
        cur.execute("SELECT id, settings_config FROM providers WHERE app_type='claude'")
        for pid, cfg_s in cur.fetchall():
            try:
                cfg = json.loads(cfg_s)
            except Exception:
                continue
            cfg, changed = patch_claude_config(cfg, claude_cmd)
            if changed:
                cur.execute(
                    "UPDATE providers SET settings_config=? WHERE id=? AND app_type='claude'",
                    (json.dumps(cfg, ensure_ascii=False), pid),
                )
                n += 1

        cur.execute("SELECT id, settings_config FROM providers WHERE app_type='codex'")
        for pid, cfg_s in cur.fetchall():
            try:
                cfg = json.loads(cfg_s)
            except Exception:
                continue
            toml_s, changed = patch_codex_toml(cfg.get("config", ""))
            if changed:
                cfg["config"] = toml_s
                cur.execute(
                    "UPDATE providers SET settings_config=? WHERE id=? AND app_type='codex'",
                    (json.dumps(cfg, ensure_ascii=False), pid),
                )
                n += 1

        conn.commit()
    except Exception as e:
        conn.rollback()
        print("  patch failed (rolled back): " + str(e))
        return
    finally:
        conn.close()

    if n > 0:
        print("  patched " + str(n) + " cc-switch provider(s)")

if __name__ == "__main__":
    main()
'''


CC_SWITCH_UNPATCH_PY = r'''#!/usr/bin/env python3
"""cc-switch compatibility cleanup: remove git-ai hooks from provider configs.
Backups db before mutating."""
import json, os, re, sqlite3, shutil, time, glob

def is_git_ai_hook(hook, agent):
    if not isinstance(hook, dict):
        return False
    cmd = hook.get("command", "")
    return isinstance(cmd, str) and ("checkpoint " + agent) in cmd

def unpatch_claude_config(cfg):
    if not isinstance(cfg, dict):
        return cfg, False
    hooks = cfg.get("hooks")
    if not isinstance(hooks, dict):
        return cfg, False
    changed = False
    for evt in ("PreToolUse", "PostToolUse"):
        blocks = hooks.get(evt)
        if not isinstance(blocks, list):
            continue
        new_blocks = []
        for block in blocks:
            if not isinstance(block, dict):
                new_blocks.append(block)
                continue
            old_hooks = block.get("hooks")
            if not isinstance(old_hooks, list):
                new_blocks.append(block)
                continue
            new_hooks = [h for h in old_hooks if not is_git_ai_hook(h, "claude")]
            if len(new_hooks) != len(old_hooks):
                changed = True
            if new_hooks:
                nb = dict(block)
                nb["hooks"] = new_hooks
                new_blocks.append(nb)
        if new_blocks:
            hooks[evt] = new_blocks
        else:
            hooks.pop(evt, None)
        if new_blocks != blocks:
            changed = True
    if not hooks:
        cfg.pop("hooks", None)
        changed = True
    else:
        cfg["hooks"] = hooks
    return cfg, changed

def unpatch_codex_toml(toml_s):
    if not isinstance(toml_s, str) or "codex_hooks" not in toml_s:
        return toml_s, False
    lines = toml_s.splitlines()
    trailing = toml_s.endswith("\n")
    out = []
    changed = False
    for line in lines:
        if re.match(r"^\s*codex_hooks\s*=\s*true\s*(?:#.*)?$", line):
            changed = True
            continue
        out.append(line)
    if not changed:
        return toml_s, False
    text = "\n".join(out)
    if trailing and text:
        text += "\n"
    text = re.sub(r"(?ms)^\[features\]\n(?=\s*(?:\n|\[|$))\s*", "", text)
    return text, True

def backup_db(db):
    ts = time.strftime("%Y%m%d-%H%M%S")
    try:
        shutil.copy2(db, db + ".bak." + ts)
    except Exception:
        pass

def main():
    db = os.path.join(os.path.expanduser("~"), ".cc-switch", "cc-switch.db")
    if not os.path.isfile(db):
        return
    backup_db(db)
    conn = sqlite3.connect(db)
    cur = conn.cursor()
    n = 0
    try:
        for pid, cfg_s in cur.execute("SELECT id, settings_config FROM providers WHERE app_type='claude'").fetchall():
            try:
                cfg = json.loads(cfg_s)
            except Exception:
                continue
            cfg, changed = unpatch_claude_config(cfg)
            if changed:
                cur.execute("UPDATE providers SET settings_config=? WHERE id=? AND app_type='claude'", (json.dumps(cfg, ensure_ascii=False), pid))
                n += 1
        for pid, cfg_s in cur.execute("SELECT id, settings_config FROM providers WHERE app_type='codex'").fetchall():
            try:
                cfg = json.loads(cfg_s)
            except Exception:
                continue
            toml_s, changed = unpatch_codex_toml(cfg.get("config", ""))
            if changed:
                cfg["config"] = toml_s
                cur.execute("UPDATE providers SET settings_config=? WHERE id=? AND app_type='codex'", (json.dumps(cfg, ensure_ascii=False), pid))
                n += 1
        conn.commit()
    except Exception as e:
        conn.rollback()
        print("  unpatch failed (rolled back): " + str(e))
        return
    finally:
        conn.close()
    if n > 0:
        print("  unpatched " + str(n) + " cc-switch provider(s)")

if __name__ == "__main__":
    main()
'''


HOOK_REPAIR_SH = r'''#!/bin/bash
# git-ai hook auto-repair. Runs every {interval} min via cron.
# Only triggers when a previously-installed hook has gone missing,
# AND backs off (max once per 30 min) to avoid loops on tools that
# install-hooks does not natively support.
GIT_AI="$HOME/.git-ai/bin/git-ai"
CLAUDE_CFG="$HOME/.claude/settings.json"
CODEX_CFG="$HOME/.codex/config.toml"
CODEX_HOOKS="$HOME/.codex/hooks.json"
STAMP="$HOME/.git-ai/.last-repair"

[ -x "$GIT_AI" ] || exit 0

# Backoff: skip if last repair < 30 min ago
if [ -f "$STAMP" ]; then
    last=$(cat "$STAMP" 2>/dev/null || echo 0)
    now=$(date +%s)
    delta=$((now - last))
    [ "$delta" -lt 1800 ] && exit 0
fi

need=false
[ -f "$CLAUDE_CFG" ] && ! grep -q "checkpoint claude" "$CLAUDE_CFG" 2>/dev/null && need=true
[ -f "$CODEX_CFG" ]  && ! grep -q "codex_hooks"      "$CODEX_CFG"  2>/dev/null && need=true
# Only check codex hooks.json if it has been created at least once;
# don't enter a loop when git-ai cannot install codex hooks.
[ -f "$CODEX_HOOKS" ] && ! grep -q "checkpoint codex" "$CODEX_HOOKS" 2>/dev/null && need=true

if [ "$need" = true ]; then
    "$GIT_AI" install-hooks 2>/dev/null
    command -v python3 >/dev/null 2>&1 \
        && [ -f "$HOME/.git-ai/bin/cc-switch-patch.py" ] \
        && python3 "$HOME/.git-ai/bin/cc-switch-patch.py" 2>/dev/null
    date +%s > "$STAMP"
fi
'''

HOOK_REPAIR_PS1 = r'''# git-ai hook auto-repair (scheduled task, every {interval} min)
# Backs off (max once per 30 min) to avoid loops.
$gitAi      = "$env:USERPROFILE\.git-ai\bin\git-ai.exe"
$claudeCfg  = "$env:USERPROFILE\.claude\settings.json"
$codexCfg   = "$env:USERPROFILE\.codex\config.toml"
$codexHooks = "$env:USERPROFILE\.codex\hooks.json"
$stamp      = "$env:USERPROFILE\.git-ai\.last-repair"

if (-not (Test-Path $gitAi)) { exit 0 }

if (Test-Path $stamp) {
    $last = 0
    try { $last = [int64](Get-Content $stamp -Raw -ErrorAction SilentlyContinue) } catch { $last = 0 }
    $now = [int64](Get-Date -UFormat %s)
    if (($now - $last) -lt 1800) { exit 0 }
}

$need = $false
if (Test-Path $claudeCfg) {
    $c = Get-Content $claudeCfg -Raw -ErrorAction SilentlyContinue
    if ($c -and $c -notmatch 'checkpoint claude') { $need = $true }
}
if (Test-Path $codexCfg) {
    $c = Get-Content $codexCfg -Raw -ErrorAction SilentlyContinue
    if ($c -and $c -notmatch 'codex_hooks') { $need = $true }
}
if (Test-Path $codexHooks) {
    $c = Get-Content $codexHooks -Raw -ErrorAction SilentlyContinue
    if ($c -and $c -notmatch 'checkpoint codex') { $need = $true }
}

if ($need) {
    & $gitAi install-hooks 2>$null
    $p = "$env:USERPROFILE\.git-ai\bin\cc-switch-patch.py"
    $py = Get-Command python3 -ErrorAction SilentlyContinue
    if (-not $py) { $py = Get-Command python -ErrorAction SilentlyContinue }
    if ($py -and (Test-Path $p)) { & $py.Path $p 2>$null }
    [int64](Get-Date -UFormat %s) | Out-File -FilePath $stamp -Encoding ASCII -Force
}
'''


# ═══════════════════════════════════════════════════════════
# Helper script endpoints (so install scripts can fetch them
# instead of embedding 30 KB of Python)
# ═══════════════════════════════════════════════════════════

@router.get("/scripts/cc-switch-patch.py", response_class=PlainTextResponse)
async def script_cc_switch_patch():
    return CC_SWITCH_PATCH_PY


@router.get("/scripts/cc-switch-unpatch.py", response_class=PlainTextResponse)
async def script_cc_switch_unpatch():
    return CC_SWITCH_UNPATCH_PY


@router.get("/scripts/git-ai-hook-repair.sh", response_class=PlainTextResponse)
async def script_hook_repair_sh():
    return HOOK_REPAIR_SH.replace("{interval}", str(INSTALL_HOOK_REPAIR_INTERVAL_MIN))


@router.get("/scripts/git-ai-hook-repair.ps1", response_class=PlainTextResponse)
async def script_hook_repair_ps1():
    return HOOK_REPAIR_PS1.replace("{interval}", str(INSTALL_HOOK_REPAIR_INTERVAL_MIN))


@router.get("/install/version", response_class=PlainTextResponse)
async def install_version():
    """Plain version string (used by client-side idempotency check)."""
    return INSTALL_GIT_AI_VERSION


# ═══════════════════════════════════════════════════════════
#  install.sh  (macOS / Linux)
# ═══════════════════════════════════════════════════════════

@router.get("/install.sh", response_class=PlainTextResponse)
async def install_sh(request: Request):
    host = request.headers.get("host", "localhost:8000")
    base_url = f"http://{host}"
    intro = _intro("install.sh")
    return rf"""{intro}
set -euo pipefail

RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[0;33m' GRAY='\033[0;90m' NC='\033[0m'
error(){{ echo -e "${{RED}}[X] $1${{NC}}" >&2; exit 1; }}
ok(){{ echo -e "${{GREEN}}[OK] $1${{NC}}"; }}
warn(){{ echo -e "${{YELLOW}}[!] $1${{NC}}"; }}
skip(){{ echo -e "${{GRAY}}  [跳过] $1${{NC}}"; }}

API_BASE_URL="{base_url}"
API_KEY="{DEFAULT_API_KEY}"
TEAM_NAME="{INSTALL_TEAM_NAME}"
REPO="{INSTALL_REPO}"
VERSION="${{GIT_AI_VERSION:-{INSTALL_GIT_AI_VERSION}}}"
GH_BASE="${{GIT_AI_GITHUB_BASE:-{INSTALL_GITHUB_BASE}}}"
GH_BASE_FALLBACK="${{GIT_AI_GITHUB_BASE_FALLBACK:-{INSTALL_GITHUB_BASE_FALLBACK}}}"
HOOK_REPAIR_INTERVAL={INSTALL_HOOK_REPAIR_INTERVAL_MIN}
USER_NAME="${{USER:-}}"
[ -n "$USER_NAME" ] || USER_NAME="$(id -un 2>/dev/null || echo)"
[ -n "$USER_NAME" ] || USER_NAME="$(git config --global --get user.name 2>/dev/null || true)"
[ -n "$USER_NAME" ] || USER_NAME="$(git config --get user.name 2>/dev/null || true)"

TOTAL=8
echo "========================================"
echo " Git-AI 一键安装 (${{TEAM_NAME}})"
echo " 服务端: ${{API_BASE_URL}}"
echo " 版本:   ${{VERSION}}"
echo "========================================"

# ── 1. Check Git ──
echo "[1/${{TOTAL}}] 检查 Git..."
command -v git >/dev/null 2>&1 || error "请先安装 Git: https://git-scm.com"
REAL_GIT=$(type -P git 2>/dev/null || command -v git)
case "$REAL_GIT" in *git-ai*) error "检测到 git-ai shim，请先卸载旧版本";; esac
ok "Git: $REAL_GIT"

# ── 2. Idempotency: skip download if same version installed ──
INSTALL_DIR="$HOME/.git-ai/bin"
mkdir -p "$INSTALL_DIR"
NEED_DOWNLOAD=true
if [ -x "$INSTALL_DIR/git-ai" ]; then
    CUR=$("$INSTALL_DIR/git-ai" --version 2>/dev/null | head -n1 | awk '{{print $NF}}')
    case "$CUR" in
        v*) ;;
        *)  CUR="v$CUR" ;;
    esac
    if [ "$CUR" = "$VERSION" ]; then
        ok "已安装目标版本 ($CUR)，跳过下载"
        NEED_DOWNLOAD=false
    else
        echo "  当前 $CUR -> 目标 $VERSION"
    fi
fi

# ── 3. Download ──
echo "[2/${{TOTAL}}] 下载 git-ai..."
if [ "$NEED_DOWNLOAD" = true ]; then
    OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    ARCH=$(uname -m)
    case "$ARCH" in x86_64) ARCH="x64" ;; aarch64|arm64) ARCH="arm64" ;; *) error "不支持的架构: $ARCH" ;; esac
    case "$OS" in darwin) OS="macos" ;; linux) OS="linux" ;; *) error "不支持的系统: $OS" ;; esac
    BINARY="git-ai-${{OS}}-${{ARCH}}"

    TMP=$(mktemp "$INSTALL_DIR/git-ai.tmp.XXXXXX")
    trap 'rm -f "$TMP" 2>/dev/null || true' EXIT

    download_one(){{
        local base="$1" url
        if [ "$VERSION" = "latest" ]; then
            url="${{base}}/${{REPO}}/releases/latest/download/${{BINARY}}"
        else
            url="${{base}}/${{REPO}}/releases/download/${{VERSION}}/${{BINARY}}"
        fi
        echo "  -> $url"
        curl -fSL --retry 3 --retry-delay 2 --retry-all-errors --progress-bar -o "$TMP" "$url"
    }}

    if ! download_one "$GH_BASE"; then
        warn "镜像下载失败，尝试 GitHub 直连..."
        download_one "$GH_BASE_FALLBACK" || error "下载失败，请检查网络"
    fi
    [ -s "$TMP" ] || error "下载文件为空"

    mv -f "$TMP" "$INSTALL_DIR/git-ai"
    chmod +x "$INSTALL_DIR/git-ai"
    trap - EXIT
fi
# git -> git-ai shim, git-og -> real git
ln -sf "$INSTALL_DIR/git-ai" "$INSTALL_DIR/git"
ln -sf "$REAL_GIT" "$INSTALL_DIR/git-og"
AI_ALIAS=$(git config --global --get alias.ai 2>/dev/null || true)
if [ -z "$AI_ALIAS" ] || printf '%s' "$AI_ALIAS" | grep -q '\.git-ai/bin/git-ai'; then
    git config --global alias.ai "!\"$INSTALL_DIR/git-ai\"" 2>/dev/null || true
else
    warn "检测到已有 git alias.ai，保留不覆盖"
fi

GIT_AI_VERSION_OUT=$("$INSTALL_DIR/git-ai" --version 2>/dev/null) || error "git-ai 自检失败，已停止安装 hooks"
ok "git-ai 已安装并通过自检: $GIT_AI_VERSION_OUT"

# ── 4. Write config.json ──
echo "[3/${{TOTAL}}] 生成配置..."
CONFIG_DIR="$HOME/.git-ai"
USER_LINE=""
[ -n "$USER_NAME" ] && USER_LINE=", \"user\": \"${{USER_NAME}}\""
if [ -n "$USER_NAME" ]; then
    mkdir -p "$CONFIG_DIR/internal"
    printf '%s\n' "$USER_NAME" > "$CONFIG_DIR/internal/distinct_id"
fi
cat > "$CONFIG_DIR/config.json" << EOFCFG
{{
  "git_path": "${{REAL_GIT}}",
  "api_base_url": "${{API_BASE_URL}}",
  "api_key": "${{API_KEY}}",
  "prompt_storage": "default",
  "feature_flags": {{ "async_mode": true }},
  "custom_attributes": {{ "team": "${{TEAM_NAME}}"${{USER_LINE}} }},
  "disable_auto_updates": true,
  "disable_version_checks": true,
  "telemetry_oss_disabled": true
}}
EOFCFG
ok "配置已生成: $CONFIG_DIR/config.json"

# ── 5. Reload daemon ──
echo "[4/${{TOTAL}}] 刷新后台服务..."
"$INSTALL_DIR/git-ai" bg shutdown 2>/dev/null || true
ok "后台服务已刷新"

# ── 6. Install hooks ──
echo "[5/${{TOTAL}}] 安装 IDE/Agent 钩子..."
if "$INSTALL_DIR/git-ai" install-hooks 2>/dev/null; then ok "钩子安装完成"; else warn "钩子安装失败，可稍后手动: git-ai install-hooks"; fi

# ── 7. cc-switch compatibility ──
echo "[6/${{TOTAL}}] cc-switch 兼容性处理..."
if curl -fsSL "${{API_BASE_URL}}/scripts/cc-switch-patch.py" -o "$INSTALL_DIR/cc-switch-patch.py"; then
    chmod +x "$INSTALL_DIR/cc-switch-patch.py"
    CC_DB="$HOME/.cc-switch/cc-switch.db"
    if [ -f "$CC_DB" ] && command -v python3 >/dev/null 2>&1; then
        if python3 "$INSTALL_DIR/cc-switch-patch.py"; then ok "cc-switch 兼容性处理完成"; else warn "cc-switch 兼容性处理失败，不影响核心功能"; fi
    else
        skip "未检测到 cc-switch 或缺少 python3"
    fi
else
    warn "cc-switch-patch.py 下载失败，跳过"
fi

# ── 8. Hook auto-repair cron ──
echo "[7/${{TOTAL}}] 配置 Hook 自动修复..."
if curl -fsSL "${{API_BASE_URL}}/scripts/git-ai-hook-repair.sh" -o "$INSTALL_DIR/git-ai-hook-repair.sh"; then
    chmod +x "$INSTALL_DIR/git-ai-hook-repair.sh"
    if command -v crontab >/dev/null 2>&1; then
        ( crontab -l 2>/dev/null | grep -v 'git-ai-hook-repair' || true
          echo "*/${{HOOK_REPAIR_INTERVAL}} * * * * $INSTALL_DIR/git-ai-hook-repair.sh >/dev/null 2>&1"
        ) | crontab -
        ok "Hook 自动修复已配置 (cron, 每 ${{HOOK_REPAIR_INTERVAL}} 分钟)"
    else
        skip "crontab 不可用，跳过自动修复配置"
    fi
else
    warn "hook-repair 脚本下载失败，跳过"
fi

# ── 9. Setup PATH ──
echo "[8/${{TOTAL}}] 配置 PATH..."
PATH_LINE='export PATH="$HOME/.git-ai/bin:$PATH"'
for rc in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.bash_profile"; do
    [ -f "$rc" ] || continue
    if ! grep -q ".git-ai/bin" "$rc" 2>/dev/null; then
        echo "$PATH_LINE" >> "$rc"
    fi
done
# fish (mkdir -p first; do NOT short-circuit if dir is missing)
mkdir -p "$HOME/.config/fish"
FISH_RC="$HOME/.config/fish/config.fish"
touch "$FISH_RC"
if ! grep -q ".git-ai/bin" "$FISH_RC" 2>/dev/null; then
    echo 'fish_add_path "$HOME/.git-ai/bin"' >> "$FISH_RC"
fi
ok "PATH 已配置"

echo ""
echo "========================================"
echo " 安装完成!"
echo "========================================"
echo ""
echo "请重新打开终端，即可正常使用 git."
echo "每次 git commit 时，AI 代码数据自动上报到:"
echo "  ${{API_BASE_URL}}"
echo ""
echo "验证: git-ai --version"
echo "========================================"
"""


# ═══════════════════════════════════════════════════════════
#  install.ps1  (Windows)
# ═══════════════════════════════════════════════════════════

@router.get("/install.ps1", response_class=PlainTextResponse)
async def install_ps1(request: Request):
    host = request.headers.get("host", "localhost:8000")
    base_url = f"http://{host}"
    intro = _intro("install.ps1")
    return rf"""{intro}
$ErrorActionPreference = 'Stop'
$ProgressPreference    = 'SilentlyContinue'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

function Pause-IfNeeded {{
    if ($env:GIT_AI_NO_PAUSE -ne "1") {{ pause }}
}}

$API_BASE_URL = "{base_url}"
$API_KEY      = "{DEFAULT_API_KEY}"
$TEAM_NAME    = "{INSTALL_TEAM_NAME}"
$REPO         = "{INSTALL_REPO}"
$VERSION      = if ($env:GIT_AI_VERSION) {{ $env:GIT_AI_VERSION }} else {{ "{INSTALL_GIT_AI_VERSION}" }}
$GH_BASE          = if ($env:GIT_AI_GITHUB_BASE) {{ $env:GIT_AI_GITHUB_BASE }} else {{ "{INSTALL_GITHUB_BASE}" }}
$GH_BASE_FALLBACK = if ($env:GIT_AI_GITHUB_BASE_FALLBACK) {{ $env:GIT_AI_GITHUB_BASE_FALLBACK }} else {{ "{INSTALL_GITHUB_BASE_FALLBACK}" }}
$HOOK_INTERVAL = {INSTALL_HOOK_REPAIR_INTERVAL_MIN}
$USER_NAME = if ($env:USERNAME) {{ $env:USERNAME }} else {{ [Environment]::UserName }}
if (-not $USER_NAME) {{
    try {{ $USER_NAME = (& git config --global --get user.name 2>$null) }} catch {{}}
}}
if (-not $USER_NAME) {{
    try {{ $USER_NAME = (& git config --get user.name 2>$null) }} catch {{}}
}}

$TOTAL = 8
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Git-AI 一键安装 ($TEAM_NAME)"           -ForegroundColor Cyan
Write-Host " 服务端: $API_BASE_URL"                   -ForegroundColor Cyan
Write-Host " 版本:   $VERSION"                        -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

# ── 1. Check Git ──
Write-Host "[1/$TOTAL] 检查 Git..." -ForegroundColor Yellow
$gitCmd = Get-Command git.exe -ErrorAction SilentlyContinue
if (-not $gitCmd) {{
    Write-Host "[X] 请先安装 Git for Windows: https://git-scm.com/download/win" -ForegroundColor Red
    Pause-IfNeeded; exit 1
}}
$REAL_GIT = $gitCmd.Path
if ($REAL_GIT -match "git-ai") {{
    Write-Host "[X] 检测到 git-ai shim，请先卸载旧版本" -ForegroundColor Red
    Pause-IfNeeded; exit 1
}}
Write-Host "  Git: $REAL_GIT" -ForegroundColor Green

$INSTALL_DIR = "$env:USERPROFILE\.git-ai\bin"
New-Item -ItemType Directory -Force -Path $INSTALL_DIR | Out-Null

# ── 2. Idempotency check ──
Write-Host "[2/$TOTAL] 检查已安装版本..." -ForegroundColor Yellow
$NEED_DOWNLOAD = $true
$gitAiExe = "$INSTALL_DIR\git-ai.exe"
if (Test-Path $gitAiExe) {{
    try {{
        $cur = (& $gitAiExe --version 2>$null | Select-Object -First 1).ToString().Trim().Split(' ')[-1]
        if ($cur -and ($cur -notlike 'v*')) {{ $cur = "v$cur" }}
        if ($cur -eq $VERSION) {{
            Write-Host "  已安装目标版本 ($cur)，跳过下载" -ForegroundColor Green
            $NEED_DOWNLOAD = $false
        }} else {{
            Write-Host "  当前 $cur -> 目标 $VERSION"
        }}
    }} catch {{}}
}}

# ── 3. Download (curl preferred) ──
Write-Host "[3/$TOTAL] 下载 git-ai..." -ForegroundColor Yellow
if ($NEED_DOWNLOAD) {{
    $ARCH   = if ($env:PROCESSOR_ARCHITECTURE -match 'ARM64') {{ "arm64" }} else {{ "x64" }}
    $BINARY = "git-ai-windows-$ARCH"
    $TMP    = "$INSTALL_DIR\git-ai.tmp.$PID.exe"

    function Download-One($base) {{
        if ($VERSION -eq "latest") {{
            $u = "$base/$REPO/releases/latest/download/$BINARY.exe"
        }} else {{
            $u = "$base/$REPO/releases/download/$VERSION/$BINARY.exe"
        }}
        Write-Host "  -> $u"
        $curl = Get-Command curl.exe -ErrorAction SilentlyContinue
        if ($curl) {{
            & $curl.Source -fL --retry 3 --retry-delay 2 --retry-all-errors -o $TMP $u
            return ($LASTEXITCODE -eq 0)
        }}
        try {{ Invoke-WebRequest -Uri $u -OutFile $TMP -UseBasicParsing -ErrorAction Stop; return $true }}
        catch {{ return $false }}
    }}

    $ok = Download-One $GH_BASE
    if (-not $ok) {{
        Write-Host "  [!] 镜像下载失败，尝试 GitHub 直连..." -ForegroundColor Yellow
        $ok = Download-One $GH_BASE_FALLBACK
    }}
    if (-not $ok) {{
        Write-Host "[X] 下载失败，请检查网络" -ForegroundColor Red
        Remove-Item $TMP -Force -ErrorAction SilentlyContinue
        Pause-IfNeeded; exit 1
    }}
    if ((Get-Item $TMP).Length -le 0) {{
        Write-Host "[X] 文件为空" -ForegroundColor Red
        Remove-Item $TMP -Force -ErrorAction SilentlyContinue
        Pause-IfNeeded; exit 1
    }}

    # Wait for the target file to be writable (anti-virus / running daemon)
    $WAIT = 0
    while ($WAIT -lt 30) {{
        try {{ $fs = [System.IO.File]::Open($gitAiExe, 'OpenOrCreate', 'Write', 'None'); $fs.Close(); break }}
        catch {{ Start-Sleep 1; $WAIT++ }}
    }}
    Move-Item -Force -Path $TMP -Destination $gitAiExe
    Unblock-File $gitAiExe -ErrorAction SilentlyContinue
}}

# git.exe shim — try SymbolicLink first (dev mode / admin), fallback to copy
$gitShim = "$INSTALL_DIR\git.exe"
Remove-Item $gitShim -Force -ErrorAction SilentlyContinue
$linked = $false
try {{
    New-Item -ItemType SymbolicLink -Path $gitShim -Target $gitAiExe -ErrorAction Stop | Out-Null
    $linked = $true
}} catch {{
    Copy-Item -Force $gitAiExe $gitShim
}}
$GIT_OG = "$INSTALL_DIR\git-og.cmd"
"@echo off`r`n`"$REAL_GIT`" %*`r`n" | Set-Content -Path $GIT_OG -Encoding ASCII -Force
try {{
    $existingAlias = (& $REAL_GIT config --global --get alias.ai 2>$null)
    if ((-not $existingAlias) -or ($existingAlias -match '\.git-ai[\\/]+bin[\\/]+git-ai')) {{
        $aliasTarget = $gitAiExe.Replace('\', '/')
        & $REAL_GIT config --global alias.ai "!`"$aliasTarget`"" 2>$null
    }} else {{
        Write-Host "  [!] 检测到已有 git alias.ai，保留不覆盖" -ForegroundColor Yellow
    }}
}} catch {{}}

try {{
    $gitAiVersionOut = & $gitAiExe --version 2>$null
    if ($LASTEXITCODE -ne 0) {{ throw "exit code $LASTEXITCODE" }}
    Write-Host "  git-ai 已安装并通过自检: $gitAiVersionOut" -ForegroundColor Green
}} catch {{
    Write-Host "[X] git-ai 自检失败: $_" -ForegroundColor Red
    Pause-IfNeeded; exit 1
}}

# ── 4. Write config.json ──
Write-Host "[4/$TOTAL] 生成配置..." -ForegroundColor Yellow
$CONFIG_DIR = "$env:USERPROFILE\.git-ai"
$utf8 = New-Object System.Text.UTF8Encoding($false)
$customAttrs = @{{ team = $TEAM_NAME }}
if ($USER_NAME) {{
    $customAttrs['user'] = $USER_NAME
    $internalDir = "$CONFIG_DIR\internal"
    New-Item -ItemType Directory -Force -Path $internalDir | Out-Null
    [System.IO.File]::WriteAllText("$internalDir\distinct_id", "$USER_NAME`n", $utf8)
}}

$CONFIG = @{{
    git_path              = $REAL_GIT
    api_base_url          = $API_BASE_URL
    api_key               = $API_KEY
    prompt_storage        = "default"
    feature_flags         = @{{ async_mode = $true }}
    custom_attributes     = $customAttrs
    disable_auto_updates  = $true
    disable_version_checks = $true
    telemetry_oss_disabled = $true
}} | ConvertTo-Json -Depth 3 -Compress

[System.IO.File]::WriteAllText("$CONFIG_DIR\config.json", $CONFIG, $utf8)
Write-Host "  配置: $CONFIG_DIR\config.json" -ForegroundColor Green

# ── 5. Reload daemon ──
Write-Host "[5/$TOTAL] 刷新后台服务..." -ForegroundColor Yellow
try {{ & $gitAiExe bg shutdown 2>$null }} catch {{}}
Write-Host "  后台服务已刷新" -ForegroundColor Green

# ── 6. Update PATH ──
Write-Host "[6/$TOTAL] 配置 PATH..." -ForegroundColor Yellow
if ($env:PATH -notlike "*$INSTALL_DIR*") {{ $env:PATH = "$INSTALL_DIR;$env:PATH" }}
try {{
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    if (-not $userPath) {{ $userPath = "" }}
    $parts = $userPath -split ';' | Where-Object {{ $_ -and ($_ -ne $INSTALL_DIR) }}
    $newPath = (@($INSTALL_DIR) + $parts) -join ';'
    [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
    Write-Host "  PATH 已更新" -ForegroundColor Green
}} catch {{
    Write-Host "  [!] PATH 更新失败，请手动将 $INSTALL_DIR 添加到 PATH" -ForegroundColor Yellow
}}

# ── 7. Install hooks ──
Write-Host "[7/$TOTAL] 安装 IDE/Agent 钩子..." -ForegroundColor Yellow
try {{
    & $gitAiExe install-hooks 2>$null
    Write-Host "  钩子安装完成" -ForegroundColor Green
}} catch {{
    Write-Host "  [!] 钩子安装失败，可稍后手动: git-ai install-hooks" -ForegroundColor Yellow
}}

# ── 8. cc-switch compatibility & hook auto-repair ──
Write-Host "[8/$TOTAL] cc-switch 兼容 + Hook 自动修复..." -ForegroundColor Yellow

$ccPatch = "$INSTALL_DIR\cc-switch-patch.py"
try {{ Invoke-WebRequest -Uri "$API_BASE_URL/scripts/cc-switch-patch.py" -OutFile $ccPatch -UseBasicParsing -ErrorAction Stop }}
catch {{ Write-Host "  [!] cc-switch-patch.py 下载失败，跳过" -ForegroundColor Yellow }}

if (Test-Path $ccPatch) {{
    $ccDb = "$env:USERPROFILE\.cc-switch\cc-switch.db"
    $py = Get-Command python3 -ErrorAction SilentlyContinue
    if (-not $py) {{ $py = Get-Command python -ErrorAction SilentlyContinue }}
    if ((Test-Path $ccDb) -and $py) {{
        try {{ & $py.Path $ccPatch 2>$null; Write-Host "  cc-switch 兼容性处理完成" -ForegroundColor Green }}
        catch {{ Write-Host "  [!] cc-switch 兼容性处理失败，不影响核心功能" -ForegroundColor Yellow }}
    }} else {{
        Write-Host "  [跳过] 未检测到 cc-switch 或缺少 Python" -ForegroundColor Gray
    }}
}}

$repairScript = "$INSTALL_DIR\git-ai-hook-repair.ps1"
try {{ Invoke-WebRequest -Uri "$API_BASE_URL/scripts/git-ai-hook-repair.ps1" -OutFile $repairScript -UseBasicParsing -ErrorAction Stop }}
catch {{ Write-Host "  [!] hook-repair.ps1 下载失败，跳过计划任务注册" -ForegroundColor Yellow }}

if (Test-Path $repairScript) {{
    try {{
        $taskShell = (Get-Command pwsh -ErrorAction SilentlyContinue).Source
        if (-not $taskShell) {{ $taskShell = "powershell.exe" }}
        $repairLauncher = "$INSTALL_DIR\git-ai-hook-repair.vbs"
        $taskShellEsc = $taskShell.Replace('"', '""')
        $repairScriptEsc = $repairScript.Replace('"', '""')
        @"
Option Explicit
Dim shell, cmd
Set shell = CreateObject("WScript.Shell")
cmd = Chr(34) & "$taskShellEsc" & Chr(34) & " -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File " & Chr(34) & "$repairScriptEsc" & Chr(34)
shell.Run cmd, 0, False
"@ | Set-Content -Path $repairLauncher -Encoding ASCII -Force

        $wscript = Join-Path $env:WINDIR "System32\wscript.exe"
        if (-not (Test-Path $wscript)) {{ $wscript = "wscript.exe" }}
        $taskAction = New-ScheduledTaskAction -Execute $wscript -Argument "`"$repairLauncher`""
        $taskTrigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) -RepetitionInterval (New-TimeSpan -Minutes $HOOK_INTERVAL)
        $taskSettings = New-ScheduledTaskSettingsSet -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Minutes 3) -MultipleInstances IgnoreNew
        Register-ScheduledTask -TaskName "GitAI-HookRepair" -Action $taskAction -Trigger $taskTrigger -Settings $taskSettings -Description "Git-AI hook auto repair" -Force | Out-Null
        Write-Host "  Hook 自动修复已配置 (计划任务, 每 $HOOK_INTERVAL 分钟，静默运行)" -ForegroundColor Green
    }} catch {{
        try {{
            $wscript = Join-Path $env:WINDIR "System32\wscript.exe"
            if (-not (Test-Path $wscript)) {{ $wscript = "wscript.exe" }}
            $tr = '"' + $wscript + '" "' + $repairLauncher + '"'
            & schtasks.exe /Create /TN "GitAI-HookRepair" /SC MINUTE /MO $HOOK_INTERVAL /TR $tr /F 2>$null | Out-Null
            if ($LASTEXITCODE -eq 0) {{
                Write-Host "  Hook 自动修复已配置 (schtasks, 每 $HOOK_INTERVAL 分钟，静默运行)" -ForegroundColor Green
            }} else {{
                Write-Host "  [!] 计划任务注册失败" -ForegroundColor Yellow
            }}
        }} catch {{
            Write-Host "  [!] 计划任务注册失败" -ForegroundColor Yellow
        }}
    }}
}}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " 安装完成!"                              -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "请关闭并重新打开终端和 IDE."
Write-Host "每次 git commit 时，数据自动上报到: $API_BASE_URL"
Write-Host ""
Write-Host "验证: git-ai --version"
Write-Host "========================================" -ForegroundColor Cyan
Pause-IfNeeded
"""


# ═══════════════════════════════════════════════════════════
#  uninstall.sh / uninstall.ps1
# ═══════════════════════════════════════════════════════════

@router.get("/uninstall.sh", response_class=PlainTextResponse)
async def uninstall_sh(request: Request):
    host = request.headers.get("host", "localhost:8000")
    base_url = f"http://{host}"
    intro = _intro("uninstall.sh")
    return rf"""{intro}
set -uo pipefail

GIT_AI="$HOME/.git-ai/bin/git-ai"
CC_DB="$HOME/.cc-switch/cc-switch.db"
API_BASE_URL="{base_url}"

echo "Git-AI 卸载开始..."

# ── 1. cc-switch rollback ──
if [ -f "$CC_DB" ] && command -v python3 >/dev/null 2>&1; then
    TMP_UNPATCH=$(mktemp -t git-ai-cc-switch-unpatch.XXXXXX.py 2>/dev/null || mktemp 2>/dev/null || echo "/tmp/git-ai-cc-switch-unpatch.$$.py")
    if curl -fsSL "${{API_BASE_URL}}/scripts/cc-switch-unpatch.py" -o "$TMP_UNPATCH"; then
        python3 "$TMP_UNPATCH" 2>/dev/null || true
    fi
    rm -f "$TMP_UNPATCH" 2>/dev/null || true
else
    echo "  [跳过] cc-switch 回滚：未检测到 cc-switch 或缺少 python3"
fi

# ── 2. git-ai cleanup ──
if [ -x "$GIT_AI" ]; then
    "$GIT_AI" uninstall-hooks --dry-run=false 2>/dev/null || true
    "$GIT_AI" bg shutdown 2>/dev/null || true
fi

# ── 3. crontab cleanup ──
if command -v crontab >/dev/null 2>&1; then
    (crontab -l 2>/dev/null | grep -v 'git-ai-hook-repair' || true) | crontab - 2>/dev/null || true
fi
AI_ALIAS=$(git config --global --get alias.ai 2>/dev/null || true)
if printf '%s' "$AI_ALIAS" | grep -q '\.git-ai/bin/git-ai'; then
    git config --global --unset alias.ai 2>/dev/null || true
fi

# ── 4. shell rc cleanup (no .bak residue) ──
clean_rc(){{
    local rc="$1"
    [ -f "$rc" ] || return 0
    # Use sed without -i to avoid leaving .bak files; write atomically.
    local tmp
    tmp=$(mktemp "${{rc}}.XXXXXX") || return 0
    grep -v '\.git-ai/bin' "$rc" > "$tmp" 2>/dev/null || cp "$rc" "$tmp"
    mv -f "$tmp" "$rc"
}}
clean_rc "$HOME/.bashrc"
clean_rc "$HOME/.zshrc"
clean_rc "$HOME/.bash_profile"
clean_rc "$HOME/.profile"
# fish
clean_rc "$HOME/.config/fish/config.fish"

# ── 5. remove install dir ──
rm -rf "$HOME/.git-ai"

echo "Git-AI 已卸载。请重新打开终端和 IDE。"
"""


@router.get("/uninstall.ps1", response_class=PlainTextResponse)
async def uninstall_ps1(request: Request):
    host = request.headers.get("host", "localhost:8000")
    base_url = f"http://{host}"
    intro = _intro("uninstall.ps1")
    return rf"""{intro}
$ErrorActionPreference = 'SilentlyContinue'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$gitAi = "$env:USERPROFILE\.git-ai\bin\git-ai.exe"
$ccDb  = "$env:USERPROFILE\.cc-switch\cc-switch.db"
$installDir = "$env:USERPROFILE\.git-ai\bin"
$API_BASE_URL = "{base_url}"

Write-Host "Git-AI 卸载开始..."

# ── 1. cc-switch rollback ──
$py = Get-Command python3 -ErrorAction SilentlyContinue
if (-not $py) {{ $py = Get-Command python -ErrorAction SilentlyContinue }}
if ((Test-Path $ccDb) -and $py) {{
    $tmpUnpatch = Join-Path $env:TEMP ("git-ai-cc-switch-unpatch-" + $PID + ".py")
    try {{
        Invoke-WebRequest -Uri "$API_BASE_URL/scripts/cc-switch-unpatch.py" -OutFile $tmpUnpatch -UseBasicParsing -ErrorAction Stop
        & $py.Path $tmpUnpatch 2>$null
    }} catch {{}}
    Remove-Item -LiteralPath $tmpUnpatch -Force -ErrorAction SilentlyContinue
}} else {{
    Write-Host "  [跳过] cc-switch 回滚：未检测到 cc-switch 或缺少 Python" -ForegroundColor Gray
}}

# ── 2. git-ai cleanup ──
if (Test-Path $gitAi) {{
    & $gitAi uninstall-hooks --dry-run=false 2>$null
    & $gitAi bg shutdown 2>$null
}}

# ── 3. scheduled task ──
foreach ($taskName in @("GitAI-HookRepair")) {{
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
    & schtasks.exe /Delete /TN $taskName /F 2>$null | Out-Null
}}
foreach ($p in @(
    "$installDir\git-ai-hook-repair.vbs",
    "$installDir\git-ai-hook-repair.ps1"
)) {{
    Remove-Item -LiteralPath $p -Force -ErrorAction SilentlyContinue
}}
try {{
    $aliasValue = (& git config --global --get alias.ai 2>$null)
    if ($aliasValue -match '\.git-ai[\\/]+bin[\\/]+git-ai') {{
        & git config --global --unset alias.ai 2>$null
    }}
}} catch {{}}

# ── 4. PATH cleanup (User scope) and refresh current process ──
$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if ($userPath) {{
    $parts = $userPath -split ';' | Where-Object {{ $_ -and ($_ -notlike '*\.git-ai\bin*') -and ($_ -notlike '*git-ai\bin*') }}
    [Environment]::SetEnvironmentVariable('Path', ($parts -join ';'), 'User')
}}
# refresh current session
$env:PATH = (($env:PATH -split ';') | Where-Object {{ $_ -and ($_ -notlike '*\.git-ai\bin*') -and ($_ -notlike '*git-ai\bin*') }}) -join ';'

# ── 5. VS Code git.path cleanup ──
$codeSettings = Join-Path $env:APPDATA 'Code\User\settings.json'
if (Test-Path $codeSettings) {{
    try {{
        $json = Get-Content $codeSettings -Raw | ConvertFrom-Json -AsHashtable
        if (($json['git.path'] -as [string]) -match '\.git-ai') {{
            $git = (Get-Command git.exe -ErrorAction SilentlyContinue).Source
            if ($git -and ($git -notmatch '\.git-ai')) {{ $json['git.path'] = $git }} else {{ $json.Remove('git.path') }}
            [System.IO.File]::WriteAllText($codeSettings, ($json | ConvertTo-Json -Depth 50), [System.Text.UTF8Encoding]::new($false))
        }}
    }} catch {{}}
}}

# ── 6. remove install dir ──
Remove-Item -LiteralPath "$env:USERPROFILE\.git-ai" -Recurse -Force -ErrorAction SilentlyContinue

Write-Host "Git-AI 已卸载。请重新打开终端和 IDE。" -ForegroundColor Green
"""
